/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brian Seoane (https://sketchfab.com/dgrafi.seoane)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-f58b4bb7fb62402ea56782a46b4b481b
Title: Macintosh
*/

import * as THREE from 'three'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GroupProps } from '@react-three/fiber'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { useRef } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Plane_0: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Cube_0: THREE.Mesh
    Plane001_0: THREE.Mesh
  }
  materials: {
    CremitaMac: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
}

interface DemoComputerProps extends GroupProps {  // Extiende GroupProps para aceptar las propiedades de un grupo
    texture?: string // Prop opcional para la textura (video o imagen)
}

export function DemoComputer({texture, ...props}: DemoComputerProps) {
    const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/models/macintosh.glb') as GLTFResult

  const txt = useVideoTexture(texture ? texture : '/textures/project/project1.mp4') 

  useGSAP(() => {
    if (group.current) {
      gsap.from(group.current.rotation, {
        y: Math.PI / 2,
        duration: 1,
        ease: 'power3.out',
      });
    }
  }, [txt]);
  
  return (
    <group  ref={group} {...props} dispose={null}>
      <group position={[-0.03, 0, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.071}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_0.geometry}
          material={materials.CremitaMac}
          position={[0.235, 0.246, 0]}
          rotation={[Math.PI / 2, 0.401, 0]}
          scale={0.427}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0.geometry}
          material={materials['Material.002']}
          position={[-0.835, 2.807, -3.517]}
          rotation={[0, 0, 0.401]}
          scale={[0.191, 0.191, 0.081]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_0.geometry}
          material={materials['Material.001']}
          position={[-1.552, -0.51, -2.057]}
          rotation={[0, 0, 0.401]}
          scale={[0.159, 0.019, 0.159]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_0.geometry}
          material={materials['Material.006']}
          position={[0.152, 0.61, 0.846]}
          rotation={[Math.PI / 2, 0.401, 0]}
          scale={[2.01, 1.526, 1]}
        >
          <meshBasicMaterial map={txt}/>  
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/macintosh.glb')

export default DemoComputer