/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WhatIsLove (https://sketchfab.com/vladgutu11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-plus-c1719ed762a7412d933f3ddef0ce2929
Title: Iphone 16 Plus
*/

import * as THREE from 'three'
import { Float, useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
    defaultMaterial_7: THREE.Mesh
    defaultMaterial_8: THREE.Mesh
    defaultMaterial_9: THREE.Mesh
    defaultMaterial_10: THREE.Mesh
    defaultMaterial_11: THREE.Mesh
    defaultMaterial_12: THREE.Mesh
    defaultMaterial_13: THREE.Mesh
  }
  materials: {
    Screen_Glass: THREE.MeshStandardMaterial
    Antenna: THREE.MeshStandardMaterial
    Glass_Camera_Logo: THREE.MeshStandardMaterial
    Back_Cover: THREE.MeshStandardMaterial
    Screen_Rim: THREE.MeshStandardMaterial
    Grill_USB: THREE.MeshStandardMaterial
    Camera_Pixel_Glass_002: THREE.MeshStandardMaterial
    Camera_Pixel__002: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Rim_Buttons: THREE.MeshStandardMaterial
    Flash_Glass_002: THREE.MeshStandardMaterial
    Flash_002: THREE.MeshPhysicalMaterial
    Screen_BG: THREE.MeshStandardMaterial
    Screw: THREE.MeshStandardMaterial
  }
}

export function Iphone16(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/iphone_16_plus.glb') as GLTFResult

  const screenTexture = useTexture('/textures/iphone16/linkedin.jpeg')
  screenTexture.repeat.set(3,6.7)
  screenTexture.offset.set(-0.55,-3 )
  screenTexture.flipY = false
  return (
    <Float {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
            {/* <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.Screen_Glass}
            /> */}
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.Antenna}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.Glass_Camera_Logo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.Back_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_4.geometry}
              material={materials.Screen_Rim}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials.Grill_USB}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.Camera_Pixel_Glass_002}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.Camera_Pixel__002}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials.Rim_Buttons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_10.geometry}
              material={materials.Flash_Glass_002}
            >
            </mesh>

            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_12.geometry}
              material={materials.Screen_BG}
            >

              <meshMatcapMaterial map={screenTexture} />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_13.geometry}
              material={materials.Screw}
            />
          </group>
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/iphone_16_plus.glb')

export default Iphone16
