/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bernardo Ferreira Baptista (https://sketchfab.com/Bernardofer)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/apple-vision-pro-1deb589878a84635bcf1e3c3d6502899
Title: Apple Vision Pro
*/

import * as THREE from 'three'
import { Float, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Visor_Frente_Visor_0: THREE.Mesh
    ['Visor_Pl��stico__Preto_0']: THREE.Mesh
    ['Visor_Pl��stico__Preto_0_1']: THREE.Mesh
    ['Visor_Pl��stico__Preto_0_2']: THREE.Mesh
    Visor_Metal_Lateral_0: THREE.Mesh
    Visor_Metal_Lateral_0_1: THREE.Mesh
    Visor_Tela_0: THREE.Mesh
    Lente_Lente_0: THREE.Mesh
    ['Bot��o_Metal_Lateral_0']: THREE.Mesh
    ['Bot��o_Luzes_0']: THREE.Mesh
    ['Apoio_olhos_Pl��stico_Branco_0']: THREE.Mesh
    Apoio_olhos_Almofada_olhos_0: THREE.Mesh
    ['Bot��o_2_Metal_Lateral_0']: THREE.Mesh
    ['Apoio_Pl��stico_Branco_0']: THREE.Mesh
    ['Apoio_Cabe��a_Almofadas_cabe��a_0']: THREE.Mesh
    ['Apoio_Cabe��a_Pl��stico__Preto_0']: THREE.Mesh
    ['Apoio_Cabe��a_Luzes_0']: THREE.Mesh
    Enchimento_Enchimento_0: THREE.Mesh
    fios_Borrachas_0: THREE.Mesh
    ['Apoio_Cabe��a001_Borrachas_0']: THREE.Mesh
  }
  materials: {
    Visor: THREE.MeshPhysicalMaterial
    Plstico__Preto: THREE.MeshStandardMaterial
    Metal_Lateral: THREE.MeshPhysicalMaterial
    Tela: THREE.MeshStandardMaterial
    Lente: THREE.MeshStandardMaterial
    Luzes: THREE.MeshStandardMaterial
    Plstico_Branco: THREE.MeshPhysicalMaterial
    Almofada_olhos: THREE.MeshStandardMaterial
    Almofadas_cabea: THREE.MeshStandardMaterial
    Enchimento: THREE.MeshStandardMaterial
    Borrachas: THREE.MeshPhysicalMaterial
  }
}

const VisionPro = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/apple_vision_pro.glb') as GLTFResult
  return (
    <Float {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.281}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[1.25, 135.252, 136.609]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Visor_Pl��stico__Preto_0'].geometry}
              material={materials.Plstico__Preto}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Visor_Pl��stico__Preto_0_1'].geometry}
              material={materials.Plstico__Preto}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Visor_Pl��stico__Preto_0_2'].geometry}
              material={materials.Plstico__Preto}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Visor_Metal_Lateral_0.geometry}
              material={materials.Metal_Lateral}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Visor_Metal_Lateral_0_1.geometry}
              material={materials.Metal_Lateral}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Visor_Tela_0.geometry}
              material={materials.Tela}
            />
          </group>
          <group
            position={[-140.664, 208.892, 121.678]}
            rotation={[-1.722, -0.341, 3.134]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Bot��o_Metal_Lateral_0'].geometry}
              material={materials.Metal_Lateral}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Bot��o_Luzes_0'].geometry}
              material={materials.Luzes}
            />
          </group>
          <group
            position={[1.855, 124.801, 43.694]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Apoio_olhos_Pl��stico_Branco_0'].geometry}
              material={materials.Plstico_Branco}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Apoio_olhos_Almofada_olhos_0.geometry}
              material={materials.Almofada_olhos}
            />
          </group>
          <group
            position={[1.158, 135.499, -323.656]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Apoio_Cabe��a_Almofadas_cabe��a_0'].geometry}
              material={materials.Almofadas_cabea}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Apoio_Cabe��a_Pl��stico__Preto_0'].geometry}
              material={materials.Plstico__Preto}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Apoio_Cabe��a_Luzes_0'].geometry}
              material={materials.Luzes}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Visor_Frente_Visor_0.geometry}
            material={materials.Visor}
            position={[1.414, 170.236, 224.865]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={135.827}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lente_Lente_0.geometry}
            material={materials.Lente}
            position={[0, 192.192, 102.473]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Bot��o_2_Metal_Lateral_0'].geometry}
            material={materials.Metal_Lateral}
            position={[143.645, 213.618, 120.636]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Apoio_Pl��stico_Branco_0'].geometry}
            material={materials.Plstico_Branco}
            position={[2.808, 125.792, -36.412]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Enchimento_Enchimento_0.geometry}
            material={materials.Enchimento}
            position={[1.573, 184.045, -432.266]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fios_Borrachas_0.geometry}
            material={materials.Borrachas}
            position={[1.415, 182.908, -472.023]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Apoio_Cabe��a001_Borrachas_0'].geometry}
            material={materials.Borrachas}
            position={[-236.546, 181.704, -234.213]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={100}
          />
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/apple_vision_pro.glb')

export default VisionPro