/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Arham Abdullah (https://sketchfab.com/arhamabdullahanimates)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-vision-pro-1bfb0f1d6d7c47469dfb5ceee491cc59
Title: Apple Vision Pro
*/

import * as THREE from 'three'
import { Float, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_111: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_137: THREE.Mesh
    Object_139: THREE.Mesh
    Object_143: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_161: THREE.Mesh
    Object_163: THREE.Mesh
    Object_165: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_185: THREE.Mesh
    Object_187: THREE.Mesh
    Object_190: THREE.Mesh
    Object_192: THREE.Mesh
    Object_194: THREE.Mesh
    Object_197: THREE.Mesh
    Object_199: THREE.Mesh
    Object_201: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_208: THREE.Mesh
    Object_211: THREE.Mesh
    Object_214: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_221: THREE.Mesh
    Object_223: THREE.Mesh
    Object_225: THREE.Mesh
    Object_228: THREE.Mesh
    Object_230: THREE.Mesh
    Object_232: THREE.Mesh
    Object_234: THREE.Mesh
    Object_236: THREE.Mesh
    Object_238: THREE.Mesh
    Object_240: THREE.Mesh
    Object_242: THREE.Mesh
    Object_244: THREE.Mesh
    Object_246: THREE.Mesh
    Object_249: THREE.Mesh
    Object_251: THREE.Mesh
    Object_253: THREE.Mesh
    Object_255: THREE.Mesh
    Object_257: THREE.Mesh
    Object_259: THREE.Mesh
    Object_261: THREE.Mesh
    Object_263: THREE.Mesh
    Object_265: THREE.Mesh
    Object_267: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_277: THREE.Mesh
  }
  materials: {
    cfENkBJbuidhJQR: THREE.MeshStandardMaterial
    oTqiLbrwcjsRgMt: THREE.MeshStandardMaterial
    VphdCyWbkVqOTZM: THREE.MeshStandardMaterial
    vooHjZuayuJGiMQ: THREE.MeshStandardMaterial
    qDOcIjVpElQVnfu: THREE.MeshStandardMaterial
    ZOxfklNhssATaVX: THREE.MeshStandardMaterial
    MQCEVrylLIUQrVK: THREE.MeshStandardMaterial
    AAfeebOMlIFREnV: THREE.MeshStandardMaterial
    euiQmuWDHAWaTrM: THREE.MeshStandardMaterial
    WSSwRvibmqaLYZi: THREE.MeshStandardMaterial
    qJCgguKxFcHIxWa: THREE.MeshStandardMaterial
    YfKnpdtpUYsluRm: THREE.MeshStandardMaterial
    BCKXYWKgOWAMzzp: THREE.MeshStandardMaterial
    XKlUGvPEIYYLEPM: THREE.MeshStandardMaterial
    ucekphvVRyoLWgE: THREE.MeshStandardMaterial
    jOkVLpNIDGFLUJe: THREE.MeshStandardMaterial
    eFnCMDGzSpQJEdf: THREE.MeshStandardMaterial
    schaJKIVUmSWLQA: THREE.MeshStandardMaterial
    uhSjoqjjxLxIJEp: THREE.MeshStandardMaterial
    xjMjLzeClXxPZiL: THREE.MeshStandardMaterial
    aAXWAJGJAtUuAVC: THREE.MeshStandardMaterial
    pqksKtWbSqRTkqv: THREE.MeshStandardMaterial
    movFhSaNkSrNKyM: THREE.MeshStandardMaterial
    cgOiivtAxUoeEfW: THREE.MeshStandardMaterial
    lMzofmcJBoknbil: THREE.MeshStandardMaterial
    JMJEizFSpcnBLBu: THREE.MeshStandardMaterial
    MyWTkmNpPcgwehb: THREE.MeshStandardMaterial
    IyRtefachzKUcBb: THREE.MeshStandardMaterial
    dULQkYmOHsuNGwk: THREE.MeshStandardMaterial
    kgpBHanvuTGSAYr: THREE.MeshStandardMaterial
    gMuXNdoZqzJLAvR: THREE.MeshStandardMaterial
    ILBWplikIEjpQFu: THREE.MeshStandardMaterial
    JEqrlnZSfFxzXyR: THREE.MeshStandardMaterial
    axobLmsfiYAnCsP: THREE.MeshStandardMaterial
    ANqxLmGmmZDkKZr: THREE.MeshStandardMaterial
    JFsLNaKevrqxAHS: THREE.MeshStandardMaterial
    JkJKKnxTIntgQHC: THREE.MeshStandardMaterial
    CLxgtuDKMkHlfIs: THREE.MeshStandardMaterial
    wHLUdvjLSAdAzpD: THREE.MeshStandardMaterial
    QTWCiCCGMSxWgbc: THREE.MeshStandardMaterial
    EgczyvedEqzqMFX: THREE.MeshStandardMaterial
    fwZBQTUFaZPSpvr: THREE.MeshStandardMaterial
    gSPFLmkAjqDsDpN: THREE.MeshStandardMaterial
    TOXCTGGcpkubhJV: THREE.MeshStandardMaterial
    hOQFVPUkStlnLZL: THREE.MeshStandardMaterial
    rtSfIyWixTDVpUY: THREE.MeshStandardMaterial
    pQhxnNuPXoHfCWe: THREE.MeshStandardMaterial
    bxAqWBgABbIjzMY: THREE.MeshStandardMaterial
    jsQvjteHecACAeR: THREE.MeshStandardMaterial
    KEnlbNmQcpvdozb: THREE.MeshStandardMaterial
    ZwfmonZpLDaDbGy: THREE.MeshStandardMaterial
    lciUnRZYuzqSpWr: THREE.MeshStandardMaterial
    dvmeoUrdxtrSUKH: THREE.MeshStandardMaterial
    fmmGyvGJVnVViXe: THREE.MeshStandardMaterial
    OthgPpktWeqGgKp: THREE.MeshStandardMaterial
  }
}

export function VisionPro(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('public/models/apple_vision_pro.glb') as GLTFResult
  return (
    <Float {...props} dispose={null} floatIntensity={0.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.cfENkBJbuidhJQR}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.oTqiLbrwcjsRgMt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.VphdCyWbkVqOTZM}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials.vooHjZuayuJGiMQ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_20.geometry}
            material={materials.qDOcIjVpElQVnfu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials.ZOxfklNhssATaVX}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.MQCEVrylLIUQrVK}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials.AAfeebOMlIFREnV}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials.AAfeebOMlIFREnV}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials.euiQmuWDHAWaTrM}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.WSSwRvibmqaLYZi}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.qJCgguKxFcHIxWa}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials.YfKnpdtpUYsluRm}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            material={materials.BCKXYWKgOWAMzzp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.XKlUGvPEIYYLEPM}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_44.geometry}
            material={materials.ucekphvVRyoLWgE}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials.jOkVLpNIDGFLUJe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_48.geometry}
            material={materials.ucekphvVRyoLWgE}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_50.geometry}
            material={materials.BCKXYWKgOWAMzzp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_53.geometry}
            material={materials.eFnCMDGzSpQJEdf}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55.geometry}
            material={materials.schaJKIVUmSWLQA}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_58.geometry}
            material={materials.uhSjoqjjxLxIJEp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_60.geometry}
            material={materials.xjMjLzeClXxPZiL}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_62.geometry}
            material={materials.aAXWAJGJAtUuAVC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_64.geometry}
            material={materials.pqksKtWbSqRTkqv}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_66.geometry}
            material={materials.uhSjoqjjxLxIJEp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_68.geometry}
            material={materials.movFhSaNkSrNKyM}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_71.geometry}
            material={materials.aAXWAJGJAtUuAVC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_73.geometry}
            material={materials.cgOiivtAxUoeEfW}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_75.geometry}
            material={materials.aAXWAJGJAtUuAVC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_78.geometry}
            material={materials.uhSjoqjjxLxIJEp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_80.geometry}
            material={materials.movFhSaNkSrNKyM}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_82.geometry}
            material={materials.xjMjLzeClXxPZiL}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_84.geometry}
            material={materials.aAXWAJGJAtUuAVC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_86.geometry}
            material={materials.pqksKtWbSqRTkqv}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_88.geometry}
            material={materials.uhSjoqjjxLxIJEp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_92.geometry}
            material={materials.lMzofmcJBoknbil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_94.geometry}
            material={materials.lMzofmcJBoknbil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_96.geometry}
            material={materials.JMJEizFSpcnBLBu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_98.geometry}
            material={materials.lMzofmcJBoknbil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_100.geometry}
            material={materials.MyWTkmNpPcgwehb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_102.geometry}
            material={materials.IyRtefachzKUcBb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_104.geometry}
            material={materials.dULQkYmOHsuNGwk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_106.geometry}
            material={materials.kgpBHanvuTGSAYr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_108.geometry}
            material={materials.qDOcIjVpElQVnfu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_111.geometry}
            material={materials.gMuXNdoZqzJLAvR}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_114.geometry}
            material={materials.IyRtefachzKUcBb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_116.geometry}
            material={materials.lMzofmcJBoknbil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_118.geometry}
            material={materials.JMJEizFSpcnBLBu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_120.geometry}
            material={materials.lMzofmcJBoknbil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_122.geometry}
            material={materials.MyWTkmNpPcgwehb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_124.geometry}
            material={materials.dULQkYmOHsuNGwk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_126.geometry}
            material={materials.kgpBHanvuTGSAYr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_128.geometry}
            material={materials.qDOcIjVpElQVnfu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_131.geometry}
            material={materials.ILBWplikIEjpQFu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_133.geometry}
            material={materials.ILBWplikIEjpQFu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_135.geometry}
            material={materials.JEqrlnZSfFxzXyR}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_137.geometry}
            material={materials.axobLmsfiYAnCsP}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_139.geometry}
            material={materials.ANqxLmGmmZDkKZr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_143.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_146.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_148.geometry}
            material={materials.JkJKKnxTIntgQHC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_151.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_153.geometry}
            material={materials.JkJKKnxTIntgQHC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_156.geometry}
            material={materials.CLxgtuDKMkHlfIs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_158.geometry}
            material={materials.wHLUdvjLSAdAzpD}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_161.geometry}
            material={materials.QTWCiCCGMSxWgbc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_163.geometry}
            material={materials.EgczyvedEqzqMFX}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_165.geometry}
            material={materials.wHLUdvjLSAdAzpD}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_168.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_170.geometry}
            material={materials.fwZBQTUFaZPSpvr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_172.geometry}
            material={materials.fwZBQTUFaZPSpvr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_174.geometry}
            material={materials.fwZBQTUFaZPSpvr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_176.geometry}
            material={materials.fwZBQTUFaZPSpvr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_178.geometry}
            material={materials.gSPFLmkAjqDsDpN}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_180.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_182.geometry}
            material={materials.fwZBQTUFaZPSpvr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_185.geometry}
            material={materials.TOXCTGGcpkubhJV}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_187.geometry}
            material={materials.fwZBQTUFaZPSpvr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_190.geometry}
            material={materials.hOQFVPUkStlnLZL}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_192.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_194.geometry}
            material={materials.rtSfIyWixTDVpUY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_197.geometry}
            material={materials.pQhxnNuPXoHfCWe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_199.geometry}
            material={materials.bxAqWBgABbIjzMY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_201.geometry}
            material={materials.jsQvjteHecACAeR}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_204.geometry}
            material={materials.pQhxnNuPXoHfCWe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_206.geometry}
            material={materials.bxAqWBgABbIjzMY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_208.geometry}
            material={materials.jsQvjteHecACAeR}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_211.geometry}
            material={materials.QTWCiCCGMSxWgbc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_214.geometry}
            material={materials.QTWCiCCGMSxWgbc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_216.geometry}
            material={materials.EgczyvedEqzqMFX}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_218.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_221.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_223.geometry}
            material={materials.QTWCiCCGMSxWgbc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_225.geometry}
            material={materials.EgczyvedEqzqMFX}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_228.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_230.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_232.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_234.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_236.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_238.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_240.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_242.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_244.geometry}
            material={materials.lciUnRZYuzqSpWr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_246.geometry}
            material={materials.dvmeoUrdxtrSUKH}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_249.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_251.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_253.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_255.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_257.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_259.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_261.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_263.geometry}
            material={materials.ZwfmonZpLDaDbGy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_265.geometry}
            material={materials.lciUnRZYuzqSpWr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_267.geometry}
            material={materials.dvmeoUrdxtrSUKH}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_270.geometry}
            material={materials.KEnlbNmQcpvdozb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_272.geometry}
            material={materials.JFsLNaKevrqxAHS}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_274.geometry}
            material={materials.fmmGyvGJVnVViXe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_277.geometry}
            material={materials.OthgPpktWeqGgKp}
          />
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('public/models/apple_vision_pro.glb')

export default VisionPro